name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
        run: |
          zip -r my-app.zip target/my-spring-boot-app-0.0.1-SNAPSHOT.jar
          aws s3 cp my-app.zip s3://my-app-bucket/my-app.zip
          aws elasticbeanstalk create-application-version \
            --application-name my-spring-boot-app \
            --version-label v1 \
            --source-bundle S3Bucket=my-app-bucket,S3Key=my-app.zip

          aws elasticbeanstalk update-environment \
            --environment-name $EB_ENV_NAME \
            --version-label v1

